function wlzwj(){
var qwqw = Ext.create('Ext.form.Panel', {
    bodyPadding: 5,
    height: '100%',
    layout: "column",
    baseCls: 'x-plain',
    items: [
	{
	    xtype: 'textfield',
	    name: 'Customer',
	    fieldLabel: '建议零售',
	    width: 250,
	    labelWidth: 80,
	    emptyText: '请输入建议零售',
	    anchor: '100%',
	},
			{
			    xtype: 'textfield',
			    name: 'Customer',
			    fieldLabel: '使用币别',
			    width: 250,
			    labelWidth: 80,
			    emptyText: '请输入使用币别',
			    anchor: '100%',
			},
			{
			    xtype: 'textfield',
			    name: 'Customer',
			    fieldLabel: '售价A',
			    width: 250,
			    labelWidth: 80,
			    emptyText: '请输入售价A',
			    anchor: '100%',
			},
			{
			    xtype: 'textfield',
			    name: 'Customer',
			    fieldLabel: '物料形态',
			    width: 250,
			    labelWidth: 80,
			    emptyText: '请输入物料形态',
			    anchor: '100%',
			},
			{
			    xtype: 'textfield',
			    name: 'Customer',
			    fieldLabel: '售价B',
			    width: 250,
			    labelWidth: 80,
			    emptyText: '请输入售价B',
			    anchor: '100%',
			},
			{
			    xtype: 'textfield',
			    name: 'Customer',
			    fieldLabel: '单价是否含税',
			    width: 250,
			    labelWidth: 80,
			    emptyText: '请输入是否含税',
			    anchor: '100%',
			},
			{
			    xtype: 'textfield',
			    name: 'Customer',
			    fieldLabel: '售价C',
			    width: 250,
			    labelWidth: 80,
			    emptyText: '请输入售价C',
			    anchor: '100%',
			},
			{
			    xtype: 'textfield',
			    name: 'Customer',
			    fieldLabel: '税目',
			    width: 250,
			    labelWidth: 80,
			    emptyText: '请输入税目',
			    anchor: '100%',
			},
			{
			    xtype: 'textfield',
			    name: 'Customer',
			    fieldLabel: '售价D',
			    width: 250,
			    labelWidth: 80,
			    emptyText: '请输入售价D',
			    anchor: '100%',
			},
			{
			    xtype: 'textfield',
			    name: 'Customer',
			    fieldLabel: '税率(%)',
			    width: 250,
			    labelWidth: 80,
			    emptyText: '请输入税率',
			    anchor: '100%',
			},
			{
			    xtype: 'textfield',
			    name: 'Customer',
			    fieldLabel: '售价E',
			    width: 250,
			    labelWidth: 80,
			    emptyText: '请输入售价E',
			    anchor: '100%',
			},
			{
			    xtype: 'textfield',
			    name: 'Customer',
			    fieldLabel: '采购提前期',
			    width: 250,
			    labelWidth: 80,
			    emptyText: '请输入采购提前期',
			    anchor: '100%',
			},
			{
			    xtype: 'textfield',
			    name: 'Customer',
			    fieldLabel: '标准进价',
			    width: 250,
			    labelWidth: 80,
			    emptyText: '请输入标准进价',
			    anchor: '100%',
			},
			{
			    xtype: 'textfield',
			    name: 'Customer',
			    fieldLabel: '主供应商',
			    width: 250,
			    labelWidth: 80,
			    emptyText: '请输入主供应商',
			    anchor: '100%',
			},
    ]
});

var qeqe = Ext.create('Ext.form.Panel', {
    bodyPadding: 5,
    height: '100%',
    layout: "column",
    baseCls: 'x-plain',
    items: [
	{
	    xtype: 'textfield',
	    name: 'Customer',
	    fieldLabel: '安全存量',
	    width: 250,
	    labelWidth: 80,
	    emptyText: '请输入安全存量',
	    anchor: '100%',
	},
			{
			    xtype: 'textfield',
			    name: 'Customer',
			    fieldLabel: '低于安全存量',
			    width: 250,
			    labelWidth: 80,
			    emptyText: '请输入低于安全存量',
			    anchor: '100%',
			},
			{
			    xtype: 'textfield',
			    name: 'Customer',
			    fieldLabel: '期初总数量',
			    width: 250,
			    labelWidth: 80,
			    emptyText: '请输入期初总数量',
			    anchor: '100%',
			},
			{
			    xtype: 'textfield',
			    name: 'Customer',
			    fieldLabel: '现有总数量',
			    width: 250,
			    labelWidth: 80,
			    emptyText: '请输入现有总数量',
			    anchor: '100%',
			},
			{
			    xtype: 'textfield',
			    name: 'Customer',
			    fieldLabel: '平均成本',
			    width: 250,
			    labelWidth: 80,
			    emptyText: '请输入平均成本',
			    anchor: '100%',
			},
			{
			    xtype: 'textfield',
			    name: 'Customer',
			    fieldLabel: '现行平均成本',
			    width: 250,
			    labelWidth: 80,
			    emptyText: '请输入现行平均成本',
			    anchor: '100%',
			},
			{
			    xtype: 'textfield',
			    name: 'Customer',
			    fieldLabel: '标准成本',
			    width: 250,
			    labelWidth: 80,
			    emptyText: '请输入标准成本',
			    anchor: '100%',
			},
			{
			    xtype: 'textfield',
			    name: 'Customer',
			    fieldLabel: '标准总成本',
			    width: 250,
			    labelWidth: 80,
			    emptyText: '请输入标准总成本',
			    anchor: '100%',
			},
			{
			    xtype: 'textfield',
			    name: 'Customer',
			    fieldLabel: '期初总成本',
			    width: 250,
			    labelWidth: 80,
			    emptyText: '请输入期初总成本',
			    anchor: '100%',
			},
			{
			    xtype: 'textfield',
			    name: 'Customer',
			    fieldLabel: '现行总成本',
			    width: 250,
			    labelWidth: 80,
			    emptyText: '请输入现行总成本',
			    anchor: '100%',
			},
    ]
});

var qrqr = Ext.create('Ext.form.Panel', {
    bodyPadding: 5,
    height: '100%',
    layout: "column",
    baseCls: 'x-plain',
    items: [
	{
	    xtype: 'textfield',
	    name: 'Customer',
	    fieldLabel: '最初出库日',
	    width: 250,
	    labelWidth: 80,
	    emptyText: '请输入最初出库日',
	    anchor: '100%',
	},
			{
			    xtype: 'textfield',
			    name: 'Customer',
			    fieldLabel: '最近出库日',
			    width: 250,
			    labelWidth: 80,
			    emptyText: '请输入最近出库日',
			    anchor: '100%',
			},
			{
			    xtype: 'textfield',
			    name: 'Customer',
			    fieldLabel: '最初入库日',
			    width: 250,
			    labelWidth: 80,
			    emptyText: '请输入最初入库日',
			    anchor: '100%',
			},
			{
			    xtype: 'textfield',
			    name: 'Customer',
			    fieldLabel: '最近入库日',
			    width: 250,
			    labelWidth: 80,
			    emptyText: '请输入最近入库日',
			    anchor: '100%',
			},
			{
			    xtype: 'textfield',
			    name: 'Customer',
			    fieldLabel: '呆滞起计天数',
			    width: 250,
			    labelWidth: 80,
			    emptyText: '请输入呆滞起计天数',
			    anchor: '100%',
			},
			{
			    xtype: 'textfield',
			    name: 'Customer',
			    fieldLabel: '停用日期',
			    width: 250,
			    labelWidth: 80,
			    emptyText: '请输入停用日期',
			    anchor: '100%',
			},
    ]
});


var tableds = Ext.create('Ext.TabPanel', {
    width: "100%",
    height: 250,
    autoScroll: true,
    bodyPadding: 5,
    items: [{ title: '基本资料', autoScroll: true, items: [qwqw] }, { title: '存量总信息', autoScroll: true, items: [qeqe] }, { title: '存量明细信息', autoScroll: true, }, { title: '交易资料', autoScroll: true, items: [qrqr] }, { title: '物料描述', autoScroll: true, }],
});




var forms = Ext.create('Ext.form.Panel', {
    bodyPadding: 5,
    height: '100%',
    layout: "column",
    baseCls: 'x-plain',
    items: [
	{
	    xtype: 'textfield',
	    name: 'Customer',
	    fieldLabel: '物料编号',
	    width: 250,
	    labelWidth: 80,
	    emptyText: '请输入物料编号',
	    anchor: '100%',
	},
			{
			    xtype: 'textfield',
			    name: 'Customer',
			    fieldLabel: '物料类别',
			    width: 250,
			    labelWidth: 80,
			    emptyText: '请输入物料类别',
			    anchor: '100%',
			},
			{
			    xtype: 'textfield',
			    name: 'Customer',
			    fieldLabel: '物料名称',
			    width: 250,
			    labelWidth: 80,
			    emptyText: '请输入物料名称',
			    anchor: '100%',
			},
			{
			    xtype: 'textfield',
			    name: 'Customer',
			    fieldLabel: '计量单位',
			    width: 250,
			    labelWidth: 80,
			    emptyText: '请输入计量单位',
			    anchor: '100%',
			},
			{
			    xtype: 'textfield',
			    name: 'Customer',
			    fieldLabel: '规格型号',
			    width: 250,
			    labelWidth: 80,
			    emptyText: '请输入规格型号',
			    anchor: '100%',
			},
			{
			    xtype: 'textfield',
			    name: 'Customer',
			    fieldLabel: '条形码编号',
			    width: 250,
			    labelWidth: 80,
			    emptyText: '请输入条形码编号',
			    anchor: '100%',
			},
			{
			    xtype: 'textfield',
			    name: 'Customer',
			    fieldLabel: '英文品名',
			    width: 250,
			    labelWidth: 80,
			    emptyText: '请输入英文品名',
			    anchor: '100%',
			}, tableds,
    ]



});






var windowst = new Ext.Window({
    width: 640,
    height: 470,
    title: "物料类主文件设定",
    closable: true,
    resizable: false, //设置是否可以改变大小
    draggable: true,
    anchor: '100%',
    items: [forms],
    bbar: [{ xtype: "splitbutton", text: '设定', width: 90 },
          { xtype: "splitbutton", text: '功能', width: 90 }],
});

return windowst;
}