//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class assignstyle
    {
        public assignstyle()
        {
            this.daassigbuymain = new HashSet<daassigbuymain>();
        }
    
        public int assignstyleid { get; set; }
        public string assignstylename { get; set; }
    
        public virtual ICollection<daassigbuymain> daassigbuymain { get; set; }
    }
}
