//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class billtui
    {
        public billtui()
        {
            this.billtutype = new HashSet<billtutype>();
            this.khls = new HashSet<khls>();
        }
    
        public string customerid { get; set; }
        public Nullable<System.DateTime> billdate { get; set; }
        public string billno { get; set; }
        public string moneystyle { get; set; }
        public string includerate { get; set; }
        public Nullable<float> huilv { get; set; }
        public int marker { get; set; }
        public Nullable<int> permitter { get; set; }
        public string ware { get; set; }
        public int checkstatus { get; set; }
    
        public virtual ICollection<billtutype> billtutype { get; set; }
        public virtual ICollection<khls> khls { get; set; }
    }
}
