//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class billtutype
    {
        public string billno { get; set; }
        public int lineid { get; set; }
        public string wuliaoid { get; set; }
        public int num { get; set; }
        public float oidprice { get; set; }
        public float discount { get; set; }
        public float sprice { get; set; }
        public float taxrate { get; set; }
        public float taxamt { get; set; }
        public float amountatax { get; set; }
        public string fromno { get; set; }
        public string fromrow { get; set; }
    
        public virtual billtui billtui { get; set; }
        public virtual wlzwj wlzwj { get; set; }
        public virtual saleck saleck { get; set; }
    }
}
