//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class branch
    {
        public branch()
        {
            this.buysearchmaster = new HashSet<buysearchmaster>();
            this.caigouqinggou = new HashSet<caigouqinggou>();
            this.orderpay = new HashSet<orderpay>();
            this.orders = new HashSet<orders>();
            this.pay = new HashSet<pay>();
            this.returnods = new HashSet<returnods>();
            this.staff = new HashSet<staff>();
            this.takeorderpay = new HashSet<takeorderpay>();
        }
    
        public string bm_id { get; set; }
        public string bm_name { get; set; }
        public string bm_ywname { get; set; }
        public string bm_beizhu { get; set; }
    
        public virtual ICollection<buysearchmaster> buysearchmaster { get; set; }
        public virtual ICollection<caigouqinggou> caigouqinggou { get; set; }
        public virtual ICollection<orderpay> orderpay { get; set; }
        public virtual ICollection<orders> orders { get; set; }
        public virtual ICollection<pay> pay { get; set; }
        public virtual ICollection<returnods> returnods { get; set; }
        public virtual ICollection<staff> staff { get; set; }
        public virtual ICollection<takeorderpay> takeorderpay { get; set; }
    }
}
