//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class buysearchdetails
    {
        public string sid { get; set; }
        public int line { get; set; }
        public string swuid { get; set; }
        public string swuname { get; set; }
        public string smodel { get; set; }
        public string sunit { get; set; }
        public Nullable<int> snum { get; set; }
        public Nullable<float> szprice { get; set; }
        public Nullable<float> szheshu { get; set; }
        public Nullable<float> sprice { get; set; }
        public Nullable<float> smoney { get; set; }
        public Nullable<float> sdacess { get; set; }
        public Nullable<float> sdtaxmoney { get; set; }
        public Nullable<float> sdtaxmoneys { get; set; }
        public Nullable<int> szengping { get; set; }
        public string soriginid { get; set; }
        public string sorigintype { get; set; }
        public string sfenremark { get; set; }
        public Nullable<int> sisdel { get; set; }
    
        public virtual buysearchmaster buysearchmaster { get; set; }
        public virtual wlzwj wlzwj { get; set; }
    }
}
