//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class buysearchmaster
    {
        public buysearchmaster()
        {
            this.buysearchdetails = new HashSet<buysearchdetails>();
        }
    
        public string stoid { get; set; }
        public string stopname { get; set; }
        public string stopid { get; set; }
        public string saddress { get; set; }
        public Nullable<System.DateTime> stodate { get; set; }
        public string stunum { get; set; }
        public System.DateTime stoydate { get; set; }
        public string stoshort { get; set; }
        public Nullable<float> sotaxrate { get; set; }
        public Nullable<float> stoistax { get; set; }
        public string stosaddress { get; set; }
        public string stomake { get; set; }
        public string stoshen { get; set; }
        public string stobuy { get; set; }
        public string stodep { get; set; }
        public string stostate { get; set; }
        public Nullable<int> stopbid { get; set; }
        public string sheader { get; set; }
        public string sfooter { get; set; }
        public string szione { get; set; }
        public string szitwo { get; set; }
        public string sremark { get; set; }
        public string stodid { get; set; }
        public Nullable<int> store { get; set; }
        public Nullable<int> sdel { get; set; }
    
        public virtual branch branch { get; set; }
        public virtual ICollection<buysearchdetails> buysearchdetails { get; set; }
        public virtual gmeans gmeans { get; set; }
        public virtual user user { get; set; }
    }
}
