//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class caigouqinggou
    {
        public caigouqinggou()
        {
            this.caigoumingxi = new HashSet<caigoumingxi>();
        }
    
        public string billno { get; set; }
        public System.DateTime billdate { get; set; }
        public int billstyleid { get; set; }
        public string billstatus { get; set; }
        public string maker { get; set; }
        public string permitter { get; set; }
        public string remark { get; set; }
        public string sumqty { get; set; }
        public int id { get; set; }
        public string qinggourenyuan { get; set; }
        public string qinggoubumen { get; set; }
        public string qinggoudepid { get; set; }
        public Nullable<int> qinggoubuyid { get; set; }
        public Nullable<int> checkshh { get; set; }
    
        public virtual branch branch { get; set; }
        public virtual buytype buytype { get; set; }
        public virtual ICollection<caigoumingxi> caigoumingxi { get; set; }
        public virtual user user { get; set; }
    }
}
