//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class clientmaster
    {
        public clientmaster()
        {
            this.billtui = new HashSet<billtui>();
            this.dingdanzhu = new HashSet<dingdanzhu>();
            this.saleck = new HashSet<saleck>();
            this.x_documents = new HashSet<x_documents>();
            this.ysbill = new HashSet<ysbill>();
            this.ysckbill = new HashSet<ysckbill>();
        }
    
        public int corpid { get; set; }
        public string fullname { get; set; }
        public string shortname { get; set; }
        public string classname { get; set; }
        public string chiefname { get; set; }
        public string personname { get; set; }
        public string taxno { get; set; }
        public string fundsattribfullname { get; set; }
        public int businessname { get; set; }
        public float fundslimit { get; set; }
        public float startadvrecv { get; set; }
        public float surpluslimit { get; set; }
        public float statreceivable { get; set; }
        public float curadvreceivable { get; set; }
        public string deliveraddress { get; set; }
        public float remainquota { get; set; }
    
        public virtual ICollection<billtui> billtui { get; set; }
        public virtual ICollection<dingdanzhu> dingdanzhu { get; set; }
        public virtual ICollection<saleck> saleck { get; set; }
        public virtual ICollection<x_documents> x_documents { get; set; }
        public virtual ICollection<ysbill> ysbill { get; set; }
        public virtual ICollection<ysckbill> ysckbill { get; set; }
    }
}
