//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class daassigbuymain
    {
        public daassigbuymain()
        {
            this.dsassignbuysub = new HashSet<dsassignbuysub>();
            this.dsassignfee = new HashSet<dsassignfee>();
        }
    
        public int billnoid { get; set; }
        public int billno { get; set; }
        public System.DateTime billdete { get; set; }
        public int assignstyleid { get; set; }
        public Nullable<int> voucheck { get; set; }
        public float mlamount { get; set; }
        public string maker { get; set; }
        public string permitter { get; set; }
        public int auditstatus { get; set; }
    
        public virtual ICollection<dsassignbuysub> dsassignbuysub { get; set; }
        public virtual ICollection<dsassignfee> dsassignfee { get; set; }
    }
}
