//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class detailorderpay
    {
        public int oid { get; set; }
        public float ypay { get; set; }
        public string froms { get; set; }
        public string fromno { get; set; }
        public string details { get; set; }
        public string info { get; set; }
        public int Ischeck { get; set; }
    
        public virtual orderpay orderpay { get; set; }
    }
}
