//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class dingdancong
    {
        public string orderbillid { get; set; }
        public int lineid { get; set; }
        public string matter { get; set; }
        public int num { get; set; }
        public float unitpricebefore { get; set; }
        public float discountrate { get; set; }
        public float unitprice { get; set; }
        public float amount { get; set; }
        public float taxate { get; set; }
        public float tax { get; set; }
        public float taxamount { get; set; }
        public System.DateTime predeleasedate { get; set; }
        public string singlesource { get; set; }
        public string did { get; set; }
    
        public virtual dingdanzhu dingdanzhu { get; set; }
        public virtual wlzwj wlzwj { get; set; }
        public virtual x_documents x_documents { get; set; }
    }
}
