//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class dingdanzhu
    {
        public dingdanzhu()
        {
            this.dingdancong = new HashSet<dingdancong>();
            this.salemx = new HashSet<salemx>();
        }
    
        public string orderbillid { get; set; }
        public int customerid { get; set; }
        public System.DateTime billdate { get; set; }
        public string custaddress { get; set; }
        public string priceoftax { get; set; }
        public string currname { get; set; }
        public string billstatus { get; set; }
        public Nullable<float> exchrate { get; set; }
        public int maker { get; set; }
        public Nullable<int> fuhe { get; set; }
        public int checkstatus { get; set; }
    
        public virtual clientmaster clientmaster { get; set; }
        public virtual ICollection<dingdancong> dingdancong { get; set; }
        public virtual user user { get; set; }
        public virtual user user1 { get; set; }
        public virtual ICollection<salemx> salemx { get; set; }
    }
}
