//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class dsassignfee
    {
        public int billnoid { get; set; }
        public int billnoline { get; set; }
        public int serno { get; set; }
        public int feeclassid { get; set; }
        public string farcclassname { get; set; }
        public string dsdetailcurr { get; set; }
        public float exchrete { get; set; }
        public float amount { get; set; }
        public float mlamount { get; set; }
    
        public virtual daassigbuymain daassigbuymain { get; set; }
        public virtual feeclass feeclass { get; set; }
    }
}
