//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class dsdsadjustsub
    {
        public int tjbillnoid { get; set; }
        public int tjbillnoline { get; set; }
        public int serno { get; set; }
        public string proid { get; set; }
        public string prodname { get; set; }
        public string prodsize { get; set; }
        public string sunit { get; set; }
        public Nullable<int> curqty { get; set; }
        public Nullable<float> lcostavh { get; set; }
        public Nullable<float> price { get; set; }
        public float amount { get; set; }
        public string itemremark { get; set; }
    
        public virtual dsdsadjustmain dsdsadjustmain { get; set; }
        public virtual wlzwj wlzwj { get; set; }
    }
}
