//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class gfmeansoay
    {
        public string gfid { get; set; }
        public int gfamount { get; set; }
        public int gfremain { get; set; }
        public string gfrecv { get; set; }
        public int gfdayofclose { get; set; }
        public string gfcredi { get; set; }
        public string gfinvotypeid { get; set; }
        public int gfstartadv { get; set; }
        public int gfstartrev { get; set; }
        public int gfcuradv { get; set; }
        public int gfcurrev { get; set; }
        public int gfunbilled { get; set; }
        public int gfadvance { get; set; }
        public int gfpauable { get; set; }
        public int gfaccrev { get; set; }
        public int line { get; set; }
    
        public virtual gmeans gmeans { get; set; }
    }
}
