//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class gmeansadeinite
    {
        public string gzid { get; set; }
        public string gzname { get; set; }
        public string gzlinkman { get; set; }
        public string gztele1 { get; set; }
        public string gztele2 { get; set; }
        public string gztele3 { get; set; }
        public string gzmobiletel { get; set; }
        public string gzbank { get; set; }
        public string gzbankid { get; set; }
        public string gzpersonname { get; set; }
        public string gztaxno { get; set; }
        public string gzcap { get; set; }
        public string gzindustry { get; set; }
        public string gzemail { get; set; }
        public string gzweb { get; set; }
        public string gzfaxno { get; set; }
        public int line { get; set; }
    
        public virtual gmeans gmeans { get; set; }
    }
}
