//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class gmeans
    {
        public gmeans()
        {
            this.buysearchmaster = new HashSet<buysearchmaster>();
            this.gfmeansoay = new HashSet<gfmeansoay>();
            this.gmeansadeinite = new HashSet<gmeansadeinite>();
            this.orders = new HashSet<orders>();
        }
    
        public string gid { get; set; }
        public string gnname { get; set; }
        public string gfullname { get; set; }
        public string genglishname { get; set; }
        public string gfullenglishname { get; set; }
        public string gattribution { get; set; }
        public string gtypeid { get; set; }
        public string gcurrency { get; set; }
    
        public virtual ICollection<buysearchmaster> buysearchmaster { get; set; }
        public virtual ICollection<gfmeansoay> gfmeansoay { get; set; }
        public virtual ICollection<gmeansadeinite> gmeansadeinite { get; set; }
        public virtual ICollection<orders> orders { get; set; }
    }
}
