//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class orders
    {
        public orders()
        {
            this.orderdetails = new HashSet<orderdetails>();
        }
    
        public string orderid { get; set; }
        public string ostoid { get; set; }
        public System.DateTime ostodate { get; set; }
        public string osperid { get; set; }
        public string ospername { get; set; }
        public string osperaddress { get; set; }
        public Nullable<float> osunittax { get; set; }
        public string otype { get; set; }
        public string obibie { get; set; }
        public string ostate { get; set; }
        public string ossongaddress { get; set; }
        public string ospercai { get; set; }
        public Nullable<int> ospercaiid { get; set; }
        public string oscaidep { get; set; }
        public string oscaidepid { get; set; }
        public string oxiangmu { get; set; }
        public string ostomemake { get; set; }
        public string ostoemcheck { get; set; }
        public string osremarks { get; set; }
        public string oshestate { get; set; }
        public string oheader { get; set; }
        public string ofooter { get; set; }
        public string ozione { get; set; }
        public string ozitwo { get; set; }
        public Nullable<int> ostoreorder { get; set; }
        public Nullable<int> osisdel { get; set; }
    
        public virtual branch branch { get; set; }
        public virtual gmeans gmeans { get; set; }
        public virtual ICollection<orderdetails> orderdetails { get; set; }
        public virtual user user { get; set; }
    }
}
