//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class orderpay
    {
        public int orid { get; set; }
        public string ono { get; set; }
        public Nullable<System.DateTime> nodate { get; set; }
        public int suppildno { get; set; }
        public string suppildname { get; set; }
        public string firstway { get; set; }
        public Nullable<float> firstmoney { get; set; }
        public string secondway { get; set; }
        public Nullable<float> secondmoney { get; set; }
        public string thirdway { get; set; }
        public Nullable<float> thirdmoney { get; set; }
        public string currency { get; set; }
        public Nullable<float> exchangerate { get; set; }
        public string style { get; set; }
        public Nullable<System.DateTime> enddate { get; set; }
        public string departmentno { get; set; }
        public string department { get; set; }
        public string exceter { get; set; }
        public string project { get; set; }
        public string checkman { get; set; }
        public int Ischeck { get; set; }
        public float TotalMoney { get; set; }
    
        public virtual branch branch { get; set; }
    }
}
