//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class pandianmingxi
    {
        public int id { get; set; }
        public string pandianlh { get; set; }
        public string matterid { get; set; }
        public string mattername { get; set; }
        public string guige { get; set; }
        public string danwei { get; set; }
        public string zhangmiansum { get; set; }
        public string pandiansum { get; set; }
        public string yingkuisum { get; set; }
        public string danjia { get; set; }
        public string yingkuimoney { get; set; }
        public string pihao { get; set; }
        public string yuanyin { get; set; }
    }
}
