//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class pandian
    {
        public int id { get; set; }
        public System.DateTime checkstorehouse { get; set; }
        public string checkdocumentsdate { get; set; }
        public string appreciationsubject { get; set; }
        public string documentsnumber { get; set; }
        public string decreasesubject { get; set; }
        public string vouchernumer { get; set; }
        public string checkpersonnel { get; set; }
        public string touchingpersonnel { get; set; }
        public string department { get; set; }
    }
}
