//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class qydetail
    {
        public int lineid { get; set; }
        public string ly { get; set; }
        public string lyno { get; set; }
        public string bz { get; set; }
        public float qymoneydetail { get; set; }
        public string ysckbillid { get; set; }
    
        public virtual ysbill ysbill { get; set; }
        public virtual ysckbill ysckbill { get; set; }
    }
}
