//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class returnods
    {
        public string rcustname { get; set; }
        public string raddrid { get; set; }
        public System.DateTime rbillrq { get; set; }
        public int rbillno { get; set; }
        public string rpriceoftax { get; set; }
        public string rcurrent { get; set; }
        public string rwareid { get; set; }
        public int rexchrate { get; set; }
        public string risdeduct { get; set; }
        public string rhesforeigntrade { get; set; }
        public int rdocument { get; set; }
        public string rpurchasingname { get; set; }
        public string rproducername { get; set; }
        public string rdepartid { get; set; }
        public string rrreviewername { get; set; }
        public string rprojectid { get; set; }
        public string rid { get; set; }
        public string rbid { get; set; }
        public Nullable<int> rqgid { get; set; }
        public int recheck { get; set; }
    
        public virtual branch branch { get; set; }
        public virtual storage storage { get; set; }
        public virtual user user { get; set; }
    }
}
