//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class rk_minxi
    {
        public string rk_id { get; set; }
        public int mx_spalten { get; set; }
        public string mx_number { get; set; }
        public string mx_name { get; set; }
        public string mx_version { get; set; }
        public string mx_dwname { get; set; }
        public Nullable<int> mx_num { get; set; }
        public Nullable<int> mx_zkqprice { get; set; }
        public Nullable<int> mx_broken { get; set; }
        public Nullable<int> mx_price { get; set; }
        public Nullable<int> mx_money { get; set; }
        public Nullable<int> mx_rate { get; set; }
        public Nullable<int> mx_amount { get; set; }
        public Nullable<int> mx_batch { get; set; }
        public Nullable<int> mx_gift { get; set; }
        public string mx_remarks { get; set; }
        public string mx_lydanbie { get; set; }
        public string mx_lydanhao { get; set; }
        public Nullable<int> ft_id { get; set; }
    
        public virtual rk_zhubiao rk_zhubiao { get; set; }
    }
}
