//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class saleck
    {
        public saleck()
        {
            this.billtutype = new HashSet<billtutype>();
            this.khls = new HashSet<khls>();
            this.salemx = new HashSet<salemx>();
            this.ysckdetail = new HashSet<ysckdetail>();
            this.ysdetail = new HashSet<ysdetail>();
        }
    
        public int customerid { get; set; }
        public Nullable<System.DateTime> saledate { get; set; }
        public string salenumber { get; set; }
        public string saleaddress { get; set; }
        public string saletype { get; set; }
        public string salecurrency { get; set; }
        public string saleshui { get; set; }
        public Nullable<float> salerate { get; set; }
        public string salewarehouse { get; set; }
        public int saletouch { get; set; }
        public int salecheck { get; set; }
        public string saleckdh { get; set; }
        public int checkstatus { get; set; }
    
        public virtual ICollection<billtutype> billtutype { get; set; }
        public virtual clientmaster clientmaster { get; set; }
        public virtual ICollection<khls> khls { get; set; }
        public virtual storage storage { get; set; }
        public virtual user user { get; set; }
        public virtual user user1 { get; set; }
        public virtual ICollection<salemx> salemx { get; set; }
        public virtual ICollection<ysckdetail> ysckdetail { get; set; }
        public virtual ICollection<ysdetail> ysdetail { get; set; }
    }
}
