//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class salemx
    {
        public int foldid { get; set; }
        public string matckdh { get; set; }
        public string matid { get; set; }
        public int matnum { get; set; }
        public Nullable<float> matzkq { get; set; }
        public Nullable<float> matbroken { get; set; }
        public Nullable<float> matprice { get; set; }
        public Nullable<float> matmoeny { get; set; }
        public Nullable<float> matratio { get; set; }
        public Nullable<float> matse { get; set; }
        public Nullable<float> mathsje { get; set; }
        public string matbz { get; set; }
        public string matlydb { get; set; }
        public string matlydh { get; set; }
    
        public virtual dingdanzhu dingdanzhu { get; set; }
        public virtual saleck saleck { get; set; }
        public virtual wlzwj wlzwj { get; set; }
        public virtual x_documents x_documents { get; set; }
    }
}
