//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class shopdetail
    {
        public int scolumn { get; set; }
        public Nullable<int> sprodid { get; set; }
        public string sprodname { get; set; }
        public string sprodsize { get; set; }
        public string sunitname { get; set; }
        public int snumber { get; set; }
        public int spricebefore { get; set; }
        public int sfolding { get; set; }
        public int sprece { get; set; }
        public int samount { get; set; }
        public int srate { get; set; }
        public int stax { get; set; }
        public int sincluded { get; set; }
        public int sbatch { get; set; }
        public int sgifts { get; set; }
        public int sdetalis { get; set; }
        public int sundilled { get; set; }
        public string sentrynote { get; set; }
        public string souce { get; set; }
        public string soucenumber { get; set; }
        public string sid { get; set; }
        public int line { get; set; }
    }
}
