//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class staff
    {
        public string ry_id { get; set; }
        public string ry_name { get; set; }
        public string bm_id { get; set; }
        public string ry_xinbie { get; set; }
        public string ry_ywname { get; set; }
        public string ry_shenfen { get; set; }
        public Nullable<System.DateTime> ry_csdate { get; set; }
        public string ry_hunyin { get; set; }
        public Nullable<System.DateTime> ry_rzdate { get; set; }
        public string ry_beizhu { get; set; }
    
        public virtual branch branch { get; set; }
    }
}
