//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class storage
    {
        public storage()
        {
            this.returnods = new HashSet<returnods>();
            this.rk_zhubiao = new HashSet<rk_zhubiao>();
            this.saleck = new HashSet<saleck>();
        }
    
        public string stoid { get; set; }
        public string stoname { get; set; }
        public string stosimplename { get; set; }
        public string stoenglishname { get; set; }
        public string stoconnecter { get; set; }
        public string stophone { get; set; }
        public string stoaddress { get; set; }
        public string storemark { get; set; }
        public Nullable<int> sdel { get; set; }
    
        public virtual ICollection<returnods> returnods { get; set; }
        public virtual ICollection<rk_zhubiao> rk_zhubiao { get; set; }
        public virtual ICollection<saleck> saleck { get; set; }
    }
}
