//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class wlzwj
    {
        public wlzwj()
        {
            this.buysearchdetails = new HashSet<buysearchdetails>();
            this.caigoumingxi = new HashSet<caigoumingxi>();
            this.dingdancong = new HashSet<dingdancong>();
            this.dsassignbuysub = new HashSet<dsassignbuysub>();
            this.dsdsadjustsub = new HashSet<dsdsadjustsub>();
            this.orderdetails = new HashSet<orderdetails>();
            this.salemx = new HashSet<salemx>();
            this.x_sal = new HashSet<x_sal>();
        }
    
        public string matid { get; set; }
        public int mattype { get; set; }
        public string matname { get; set; }
        public string matjldw { get; set; }
        public string matywpm { get; set; }
        public Nullable<float> matjysj { get; set; }
        public Nullable<float> mata { get; set; }
        public Nullable<float> matb { get; set; }
        public string matbb { get; set; }
        public string matsfhs { get; set; }
        public Nullable<float> matsl { get; set; }
        public Nullable<System.DateTime> matcgdate { get; set; }
        public Nullable<float> matbzjj { get; set; }
        public string matgys { get; set; }
    
        public virtual ICollection<buysearchdetails> buysearchdetails { get; set; }
        public virtual ICollection<caigoumingxi> caigoumingxi { get; set; }
        public virtual ICollection<dingdancong> dingdancong { get; set; }
        public virtual ICollection<dsassignbuysub> dsassignbuysub { get; set; }
        public virtual ICollection<dsdsadjustsub> dsdsadjustsub { get; set; }
        public virtual ICollection<orderdetails> orderdetails { get; set; }
        public virtual ICollection<salemx> salemx { get; set; }
        public virtual ICollection<x_sal> x_sal { get; set; }
    }
}
