//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class x_documents
    {
        public x_documents()
        {
            this.dingdancong = new HashSet<dingdancong>();
            this.salemx = new HashSet<salemx>();
            this.x_sal = new HashSet<x_sal>();
        }
    
        public string x_documentsid { get; set; }
        public int customerid { get; set; }
        public System.DateTime date { get; set; }
        public System.DateTime deliverodsdate { get; set; }
        public System.DateTime effective { get; set; }
        public string currname { get; set; }
        public int priceincluded { get; set; }
        public float exchange { get; set; }
        public int touching { get; set; }
        public int fuhe { get; set; }
        public int checkstatus { get; set; }
    
        public virtual clientmaster clientmaster { get; set; }
        public virtual ICollection<dingdancong> dingdancong { get; set; }
        public virtual ICollection<salemx> salemx { get; set; }
        public virtual user user { get; set; }
        public virtual user user1 { get; set; }
        public virtual ICollection<x_sal> x_sal { get; set; }
    }
}
