//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class x_sal
    {
        public int lineid { get; set; }
        public string x_documentsid { get; set; }
        public int quantity { get; set; }
        public float discountprice { get; set; }
        public float broken { get; set; }
        public float price { get; set; }
        public float amount { get; set; }
        public float taxrate { get; set; }
        public float tax { get; set; }
        public float taxincludedprice { get; set; }
        public float complimentary { get; set; }
        public string remarks { get; set; }
        public string matter { get; set; }
    
        public virtual wlzwj wlzwj { get; set; }
        public virtual x_documents x_documents { get; set; }
    }
}
