//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ysckbill
    {
        public ysckbill()
        {
            this.khls = new HashSet<khls>();
            this.qydetail = new HashSet<qydetail>();
            this.ysckdetail = new HashSet<ysckdetail>();
        }
    
        public int customerid { get; set; }
        public string ysckbillid { get; set; }
        public System.DateTime ysckbilldate { get; set; }
        public string ysckcurrname { get; set; }
        public float ysckexchrate { get; set; }
        public string ysckone { get; set; }
        public string yscktwo { get; set; }
        public string ysthree { get; set; }
        public float ysckmoney1 { get; set; }
        public float ysckmoney2 { get; set; }
        public Nullable<float> ysckmoney3 { get; set; }
        public int ysckzd { get; set; }
        public int yscksh { get; set; }
        public Nullable<float> ysckzhe { get; set; }
        public int checkstatus { get; set; }
    
        public virtual clientmaster clientmaster { get; set; }
        public virtual ICollection<khls> khls { get; set; }
        public virtual ICollection<qydetail> qydetail { get; set; }
        public virtual user user { get; set; }
        public virtual user user1 { get; set; }
        public virtual ICollection<ysckdetail> ysckdetail { get; set; }
    }
}
