//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ysckdetail
    {
        public string ysckbillid { get; set; }
        public int lineid { get; set; }
        public string ysckdetailly { get; set; }
        public string ysckdetaillyno { get; set; }
        public float yuandanmoney { get; set; }
        public Nullable<float> zherangmoney { get; set; }
        public float chongkuanmoney { get; set; }
        public float chongdimoney { get; set; }
        public float xianxingmoney { get; set; }
    
        public virtual saleck saleck { get; set; }
        public virtual ysckbill ysckbill { get; set; }
    }
}
