//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ysdetail
    {
        public string ysbillid { get; set; }
        public int lineid { get; set; }
        public string ly { get; set; }
        public string lyno { get; set; }
        public float ysmoney { get; set; }
        public float ysyue { get; set; }
    
        public virtual saleck saleck { get; set; }
    }
}
